version: '3.2'
services:
  db:
    image: mongo:3.2
    volumes:
      - ./datastore/db:/data/db
      - ./datastore/configdb:/data/configdb
  sos:
    build:
      context: webapp
    ports:
      - "8280:8280"
    volumes:
      - ./store:/tmp

networks:
  default:
    external:
      name: videothumbnail